### ISSUE TITLE
Iconv의 conv 메소드 없음

### ISSUE THREAD

**Issue by a2m** [bayja/korean_zipcode_finder#2]
korean_zipcode_finder.rb 의 19번줄에 iconv.conv 메소드를 부릅니다.

Iconv instance method 중에 `conv` 이란 메소드가 없습니다.

`iconv` 메소드로 바꿔야 될 것 같습니다.

**Comment by bayja** [comment]
http://www.ruby-doc.org/stdlib-1.9.3/libdoc/iconv/rdoc/Iconv.html#method-c-conv

conv method가 있는 걸로 알고 있는데요.
에러가 나는 ruby version이 어떻게 되나요?

**Comment by a2m** [comment]
jruby 1.7.0 (1.9.3p203) 

http://rubydoc.info/gems/iconv/0.1/Iconv 보시면 instance method 중 conv 없어보이네요.

**Comment by bayja** [comment]
오. jruby에는 conv가 없군요.
범용적으로 쓰려면 iconv로 바꾸는게 좋겠네요.
