### ISSUE TITLE
API 검색 결과 없음

### ISSUE THREAD

**Issue by a2m** [bayja/korean_zipcode_finder#3]
뭐로 검색 해도 API 검색 결과가 비었습니다 (예: 반석동, 명동).

(메시지 : `검색된 우편번호가 없습니다.`)

엔코딩 문재인지, API 자체오류인지는 확인 필요 할것 같습니다.

**Comment by a2m** [comment]
다음 HTML으로 검색 해보니까 결과가 잘 나옵니다.  엔코딩 문제 인듯 하네요.

``` html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=euc-kr">
</head>
<body>
<form method="post" action="http://biz.epost.go.kr/KpostPortal/openapi" />
<input type=hidden name="regkey" value="{api_key}" />
<input type=hidden name="target" value="post" />
<input type="text" name="query" />
<input type="submit" value="검색" />
</form>
</body>
</html>
```

**Comment by bayja** [comment]
irb에서 실행했을 때도 결과값이 안 나오나요?
api_key가 잘못 세팅되었을 경우에도 빈 array가 return됩니다.
korean_zipcode_finder의 기본 인코딩은 utf-8입니다.

require 'korean_zipcode_finder'
KoreanZipcodeFinder.configure {|c| c.api_key = 'my_api_key'}
KoreanZipcodeFinder.find_zipcode('망원동')

**Comment by a2m** [comment]
API 키 설정을 제대로 안해서 결과 없었던것입니다.
